<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Políticas de Privacidade') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            <div class="p-4 sm:p-8 bg-white dark:bg-gray-800 shadow sm:rounded-lg">
                <div class="max-w-7xl dark:text-gray-200">
                    <p class="mb-6">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget neque at eros tempus rutrum. Cras posuere faucibus mollis. Proin eu ligula maximus, aliquam magna eget, consequat mi. Nullam ac tellus in neque fermentum posuere in quis lectus. Nunc suscipit porttitor felis a cursus. Vivamus hendrerit erat nec ultricies vestibulum. Maecenas vel faucibus dui. Aliquam erat volutpat. Ut vitae nisi ultricies, suscipit turpis a, congue metus. Mauris massa felis, feugiat et nulla sed, ultrices ornare magna. Proin dapibus eleifend ipsum, ac posuere purus tristique quis. Cras lacinia ligula lectus, scelerisque sollicitudin nisi molestie in. In hendrerit magna eu laoreet aliquam. Duis placerat odio orci, vitae varius libero placerat ut.</p>
                    <p class="mb-6">Pellentesque tempus, erat ut suscipit imperdiet, justo urna pellentesque neque, ut rhoncus augue nunc sit amet risus. Cras quam turpis, rutrum sit amet pulvinar eu, dictum nec metus. Suspendisse dui nisl, eleifend nec dui vitae, varius dignissim velit. Vestibulum dignissim sit amet tortor ut sagittis. Nam id quam eget ex fringilla pulvinar ut pulvinar ligula. Vivamus arcu tortor, vulputate dignissim tincidunt et, tempus eget velit. Vivamus nec turpis non nibh ultricies dapibus. Aenean sed tortor non libero euismod eleifend. Aliquam eget ipsum sed tortor aliquet volutpat hendrerit nec justo. Nunc feugiat libero mauris. Cras iaculis ante justo, nec accumsan magna scelerisque a. Donec maximus vehicula cursus. Nulla semper odio eget congue accumsan. Integer aliquet porttitor orci faucibus gravida. Duis fermentum pulvinar nibh at imperdiet. Ut risus lectus, eleifend in magna eget, blandit porta sapien.</p>
                    <p class="mb-6">Pellentesque sed venenatis mauris, quis facilisis tellus. Aenean ullamcorper aliquet arcu, at lacinia neque volutpat eget. Proin id orci nec ex sodales facilisis ut eget lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce imperdiet est et dapibus porta. Quisque iaculis, nibh auctor tincidunt ultricies, libero lacus pretium odio, in elementum lectus nunc quis turpis. Fusce convallis molestie nibh, eget consectetur nibh sodales in. Donec gravida nisl enim, ut porta elit convallis eget. Fusce vitae ornare neque, nec consectetur leo. Vestibulum vitae lectus tristique, pretium mi eu, rhoncus lacus. Donec tincidunt bibendum est, a tincidunt magna porttitor in. Vivamus fermentum augue in orci rhoncus, ut porttitor arcu auctor. Donec semper non mi in egestas. Donec egestas dictum diam, eu cursus eros sagittis id. Suspendisse dapibus tellus arcu, ut sodales velit vestibulum sit amet. Etiam aliquet cursus felis ac ultrices.</p>
                    <p class="mb-6">Nullam mauris sapien, convallis et lacinia vitae, suscipit vitae nulla. Aenean non suscipit ex, vel varius erat. Duis sagittis, nulla vitae molestie tristique, lectus sapien consectetur nunc, in efficitur risus libero sit amet felis. Aenean nec venenatis lorem. Duis ullamcorper est eget ligula vulputate facilisis. Morbi iaculis, velit vel bibendum rutrum, massa odio vehicula est, quis pellentesque turpis tortor a libero. Ut lacinia dui ut auctor imperdiet. Quisque molestie eu tortor ac malesuada. Praesent at metus iaculis magna consequat convallis nec vitae libero. Etiam varius, lacus sed lobortis consectetur, odio magna ultricies enim, lobortis dictum mauris velit vitae nibh.</p>
                    <p class="mb-6">Praesent sed magna accumsan, dignissim nisl id, vehicula mi. Sed vehicula sem at semper malesuada. Aenean blandit quis urna ac varius. In ac rutrum enim, quis pulvinar metus. Donec finibus arcu et lectus lacinia laoreet. Nulla facilisi. Morbi scelerisque in diam ac mollis. Nam erat erat, imperdiet vel cursus non, euismod ac felis. Cras facilisis erat a vestibulum consectetur. Cras accumsan dignissim porta. Suspendisse potenti. Phasellus in ipsum non metus lobortis sodales et eget est.</p>
                </div>
            </div>

        </div>
    </div>
</x-app-layout>
